services:
  qhcc-consul-server:
    container_name: qhcc-consul-server
    image: qhcc/consul:1.19.0
    build: ./docker/consul
    volumes:
     - ./docker/consul/config/server.json:/consul/config/server.json
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      - localdev
    command: "agent"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8500/v1/status/leader || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s
  qhcc-consul-client1:
    image: qhcc/consul:1.19.0
    build: ./docker/consul
    container_name: qhcc-consul-client1
    volumes:
     - ./docker/consul/config/client1.json:/consul/config/client.json
     - ./docker/consul/config/intension-config-entry.json:/intension-config-entry.json
    network_mode: "service:qhcc-countingservice"
    command: "agent"
    depends_on:
      qhcc-consul-server:
        condition: service_healthy
      qhcc-countingservice:
        condition: service_healthy
  qhcc-consul-client2:
    image: qhcc/consul:1.19.0
    build: ./docker/consul
    container_name: qhcc-consul-client2
    volumes:
     - ./docker/consul/config/client2.json:/consul/config/client.json
    network_mode: "service:qhcc-dashboardservice"
    command: "agent"
    depends_on:
      qhcc-consul-server:
        condition: service_healthy
      qhcc-dashboardservice:
        condition: service_healthy
  qhcc-countingservice:
    image: qhcc/countingservice:0.0.3.1
    build: ./docker/countingservice
    container_name: qhcc-countingservice
    networks:
      - localdev
    environment:
      - PORT=9003
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:9003/ || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s
  qhcc-dashboardservice:
    image: qhcc/dashboardservice:0.0.3.1
    build: ./docker/dashboardservice
    container_name: qhcc-dashboardservice
    networks:
      - localdev
    environment:
      - PORT=9004
      - COUNTING_SERVICE_URL=http://localhost:5000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:9004/ || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s
    ports:
      - 9004:9004
networks:
  localdev:
